POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkcmVpIiwiaWQiOiI2MmNhNTFhYzdkZjgwZGYwOTljOGI3MTAiLCJpYXQiOjE2NTc1NDg5ODR9.9mDaxw8JS1Wx-QVSGfw59EkfupR4zUjariaYgQuwviU

{
    "title":"Blog for POST request test #9",
    "author": "dev",
    "url": "http://foo.com",
    "likes":3
}