POST http://localhost:3003/api/users
Content-Type: application/json

# {
#     "username":"kyo",
#     "name":"kyoto",
#     "password":"namekusei"
# }

{
    "username": "Adrei",
    "name": "momo ommo",
    "password": "genericPassword2"
}