POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkcmVpIiwiaWQiOiI2MmNhNTFhYzdkZjgwZGYwOTljOGI3MTAiLCJpYXQiOjE2NTc0NDI3MDR9.YR0EV-Jv1DlxHPIHJw45Hv0Lm0poBSSeuq39gxuR4es

{
    "title":"Blog for POST request test #2",
    "author": "dev",
    "url": "http://foo.com",
    "likes":3
}